import { queryContent } from "#content";

/**
 * Represents a single news article pulled from the `content/news` directory.
 */
export interface NewsItem {
  /**
   * Unique identifier generated by the content module for the document.
   */
  _id: string;
  /**
   * Route path that Nuxt Content resolves for the document.
   */
  _path: string;
  /**
   * Optional ISO 8601 date string used for chronological sorting.
   */
  date?: string;
  /**
   * Manual sort override. Higher values float an article within the same day.
   */
  order?: number;
  /**
   * Human-friendly article title sourced from front matter.
   */
  title?: string;
  /**
   * Slug assigned in the Markdown front matter for canonical linking.
   */
  slug?: string;
  /**
   * Featured image associated with the article, if provided.
   */
  image?: {
    path?: string;
    alt?: string;
  };
  /**
   * Optional hero image used on dedicated article pages.
   */
  imageHeader?: {
    path?: string;
    alt?: string;
  };
  /**
   * Arbitrary Markdown or HTML body content rendered by Nuxt Content.
   */
  body?: unknown;
  /**
   * Markers added by the content module when a document is treated as a draft.
   */
  draft?: boolean;
  _draft?: boolean;
}

/**
 * Configuration accepted by {@link useNews} for tailoring the returned dataset.
 */
export interface UseNewsOptions {
  /**
   * Limits the number of news items returned. When omitted, all articles are returned.
   */
  limit?: number;
  /**
   * When `true`, include documents flagged as drafts. Drafts are excluded by default.
   */
  includeDrafts?: boolean;
}

/**
 * Fetches news articles from the `content/news` directory sorted by publish date (newest first)
 * and, secondarily, by the optional manual `order` field.
 *
 * @example
 * const { data: news } = await useNews({ limit: 6 })
 */
export function useNews(options: UseNewsOptions = {}) {
  const { limit, includeDrafts = false } = options;
  const key = `news-${includeDrafts ? "with-drafts" : "published"}-${limit ?? "all"}`;

  return useAsyncData(key, async () => {
    const items = (await queryContent<NewsItem>("news")
      .sort({ date: -1, order: -1 })
      .find()) as NewsItem[];

    const filtered = includeDrafts
      ? items
      : items.filter(entry => entry.draft !== true && entry._draft !== true);

    return typeof limit === "number" ? filtered.slice(0, limit) : filtered;
  });
}
