import { queryCollection } from "#imports";

/**
 * Represents a single news article pulled from the `content/news` directory.
 */
export interface NewsItem {
  /**
   * Unique identifier generated by the content module for the document.
   */
  _id: string;
  /**
   * Route path that Nuxt Content resolves for the document.
   */
  _path: string;
  /**
   * Optional ISO 8601 date string used for chronological sorting.
   */
  date?: string;
  /**
   * Manual sort override. Higher values float an article within the same day.
   */
  order?: number;
  /**
   * Human-friendly article title sourced from front matter.
   */
  title?: string;
  /**
   * Slug assigned in the Markdown front matter for canonical linking.
   */
  slug?: string;
  /**
   * Featured image associated with the article, if provided.
   */
  image?: {
    path?: string;
    alt?: string;
  };
  /**
   * Optional hero image used on dedicated article pages.
   */
  imageHeader?: {
    path?: string;
    alt?: string;
  };
  /**
   * Arbitrary Markdown or HTML body content rendered by Nuxt Content.
   */
  body?: unknown;
  /**
   * Markers added by the content module when a document is treated as a draft.
   */
  draft?: boolean;
  _draft?: boolean;
}

/**
 * Configuration accepted by {@link useNews} for tailoring the returned dataset.
 */
export interface UseNewsOptions {
  /**
   * Limits the number of news items returned. When omitted, all articles are returned.
   */
  limit?: number;
  /**
   * When `true`, include documents flagged as drafts. Drafts are excluded by default.
   */
  includeDrafts?: boolean;
}

/**
 * Fetches news articles from the `content/news` directory sorted by publish date (newest first)
 * and, secondarily, by the optional manual `order` field.
 *
 * @example
 * const { data: news } = await useNews({ limit: 6 })
 */
export function useNews(options: UseNewsOptions = {}) {
  const { limit, includeDrafts = false } = options;
  const key = `news-${includeDrafts ? "with-drafts" : "published"}-${limit ?? "all"}`;

  return useAsyncData(key, async () => {
    const rows = (await queryCollection("content")
      .select("id", "path", "title", "meta")
      .where("path", "LIKE", "/news/%")
      .all()) as Array<Record<string, unknown>>;

    const parseDate = (value?: string) => {
      if (!value) {
        return 0;
      }

      const timestamp = Date.parse(value);
      return Number.isNaN(timestamp) ? 0 : timestamp;
    };

    const normalized = rows.map((row) => {
      const rawMeta = row.meta;
      const meta = typeof rawMeta === "string"
        ? (() => {
          try {
            return JSON.parse(rawMeta) as Record<string, unknown>;
          } catch {
            return {} as Record<string, unknown>;
          }
        })()
        : (rawMeta as Record<string, unknown> | undefined) ?? {};

      return {
        _id: typeof row.id === "string" ? row.id : String(row.id ?? ""),
        _path: typeof row.path === "string" ? row.path : String(row.path ?? ""),
        title: typeof row.title === "string" ? row.title : (meta.title as string | undefined),
        date: typeof meta.date === "string" ? meta.date : undefined,
        order: typeof meta.order === "number" ? meta.order : typeof meta.order === "string" ? Number(meta.order) : undefined,
        slug: typeof meta.slug === "string" ? meta.slug : undefined,
        image: typeof meta.image === "object" ? (meta.image as NewsItem["image"]) : undefined,
        imageHeader: typeof meta.imageHeader === "object" ? (meta.imageHeader as NewsItem["imageHeader"]) : undefined,
        body: undefined,
        draft: meta.draft === true,
        _draft: meta._draft === true,
      } as NewsItem;
    });

    const sorted = normalized.sort((first, second) => {
      const dateDifference = parseDate(second.date) - parseDate(first.date);

      if (dateDifference !== 0) {
        return dateDifference;
      }

      const firstOrder = typeof first.order === "number" ? first.order : 0;
      const secondOrder = typeof second.order === "number" ? second.order : 0;

      return secondOrder - firstOrder;
    });

    const published = includeDrafts
      ? sorted
      : sorted.filter(entry => entry.draft !== true && entry._draft !== true);

    return typeof limit === "number" ? published.slice(0, limit) : published;
  });
}
